#!/usr/bin/env ruby

MOMENTUM_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
MOMENTUM_ENV = ENV['MOMENTUM_ENV'] || 'development'
# MOMENTUM_DAEMON = true

if File.exist?(File.join(MOMENTUM_ROOT, 'lib', 'momentum.rb'))
  $:.unshift(File.join(MOMENTUM_ROOT, 'lib'))
end

require 'momentum'
require 'momentum/process'